export default {
  products: [
    {
      name: "Grey Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 25,
      brand: "Gap",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Black Shirt",
      category: "Shirts",
      image: "/images/d2.jpg",
      price: 30,
      brand: "Gap",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "White Shirt",
      category: "Shirts",
      image: "/images/d3.jpg",
      price: 25,
      brand: "Gap",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Red Shirt",
      category: "Shirts",
      image: "/images/d4.jpg",
      price: 25,
      brand: "Gap",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Olive Shirt",
      category: "Shirts",
      image: "/images/d5.jpg",
      price: 25,
      brand: "Gap",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
